services:
  database:
    ports:
      - 5432:5432
    container_name: container_postgresql
    image: postgres
    environment:
      - POSTGRES_DB=imaginary-products
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
#    restart: always
  backend:
    build: .
    ports:
      - 8080:8080
    container_name: container_spring_boot
    env_file:
      - ./src/main/resources/application.properties
    environment:
      - spring.datasource.url=jdbc:postgresql://database:5432/imaginary-products
      - spring.jpa.properties.hibernate.default_schema=public
    depends_on:
      - database
#    restart: always
